[package]
authors = ["William Darian <williamdariansutedjo@gmail.com>"]
categories = ["api-bindings"]
edition = "2018"
name = "jikan"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
chrono = {version = "0.4.19", features = ["serde"]}
derive-getters = "0.2.0"
futures = "0.3.8"
lazy_static = "1.4.0"
reqwest = {version = "0.10.10", features = ["json"]}
serde = {version = "1.0.118", features = ["derive"]}
serial_test = "0.5.1"
tokio = {version = "0.3.6", features = ["macros", "rt", "rt-multi-thread"]}

[dev-dependencies]
rand = "0.8.0"

[features]
default = ["anime", "manga"]

anime = []
manga = []
